config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root 'tasks#index'

end

app/models/task.rb
class Task
  include Mongoid::Document
  field :title, type: String
  field :content, type: String
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @task = Task.new
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
        format.js
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ajaxapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="col-md-4 blog-main box text-center" id="task_<%= task.id %>">
  <div class="panel panel-info"><!-- Panel Info -->
    <div class="panel-heading">
      <h3 class="panel-title"><%= task.title %></h3>
      <p><%= task.content %></p>
    </div>
    <div class="panel-body"><!-- Panel Body -->
      <!--<%# <div style="color: #3BB2D6;"><%= time_ago_in_words(task.created_at) %></div> %>-->
      <br>
      <div class="btn-group" role="group" aria-label="...">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myupdatepost_<%= task.id %>">Update</button>
        <%= link_to 'Destroy', task, method: :delete, class: "btn btn-danger", remote: true %>
      </div>
    </div><!-- Panel Body -->
  </div><!-- Panel Info -->

  <!-- Modal -->
  <%= form_for(task, :method => :put, remote: true) do |f| %>
    <div class="modal fade" id="myupdatepost_<%= task.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="field">
              <%= f.label :title %><br>
              <%= f.text_area :title, class: "form-control" %>
            </div>
            <div class="field">
              <%= f.label :content %><br>
              <%= f.text_area :content, class: "form-control" %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" id="myupdatebutton_<%= task.id %>" class="btn btn-default" data-bs-dismiss="modal">Close</button>
            <%= submit_tag "Update", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/create.js.erb
$("#mynewpost").modal('hide');
$(".task_title").val('');
$(".task_content").val('');

<% if(@task.errors.any?) %>
  alert("Title and content should not be blank")
<% else %>
  $("#container_posts").prepend('<%= j render @task %>');
  $("#task_<%= @task.id %>").hide().fadeIn(1000);
<% end %>

app/views/tasks/destroy.js.erb
$("#task_<%= @task.id %>").fadeOut(500, function(){
	$(this).remove();
});

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="text-center">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#mynewpost">Add Task</button>
    </div>
  </div>
  <br>
  <hr>
  <div class="row" id="container_posts">
    <div class="container row">
      <%= render @tasks %>
    </div>
  </div>
  <!-- Modal -->
  <%= form_for(@task, remote: true) do |f| %>
    <div class="modal fade" id="mynewpost" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="field">
              <%= f.label :title %>
              <%= f.text_area :title, class: "form-control task_title" %>
            </div>
            <div class="field">
              <%= f.label :content %>
              <%= f.text_area :content, class:"form-control task_content"%>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-bs-dismiss="modal" id="mynewpostclose">Close</button>
            <%= submit_tag "Create", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$("#myupdatepost_<%= @task.id %>").modal('hide');


$("#task_<%= @task.id %>").fadeOut(500, function(){
  $(this).remove();
	$("#container_posts").prepend('<%= j render @task %>')
});